# MongoDB image
FROM mongo:4.4

# Set the environment variable for the database name
ENV MONGO_INITDB_DATABASE sensors

# Copy the initialization script
COPY server/init-mongo.js /docker-entrypoint-initdb.d/

# Set timezone to Europe/Madrid
ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

# Expose port 27017 for MongoDB
EXPOSE 27017
