version: '3.9'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: mongodb
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
    mongodb-data:
