version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: sensors
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'

  sensor-app:
    build: .
    container_name: sensor-app
    environment:
      MONGO_URI: mongodb://mongodb:27017/sensors
      NODE_ENV: development
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    name: mongodb_data
